/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.geom.RoundRectangle2D;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Shape;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ORLANDO
 */



public class asistencia2 extends javax.swing.JFrame {

    DefaultTableModel model; //searchhhhhh
    SQLcon cc=new SQLcon();
    Connection con=cc.conexion();
    
    
    
    
    
    public asistencia2() {
    
        initComponents();
        this.setLocationRelativeTo(null);
        showdata();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        T_user = new javax.swing.JTextField();
        T_givenname = new javax.swing.JTextField();
        T_surname = new javax.swing.JTextField();
        T_email = new javax.swing.JTextField();
        T_phone = new javax.swing.JTextField();
        T_birthy = new javax.swing.JTextField();
        T_search = new javax.swing.JTextField();
        B_create = new javax.swing.JButton();
        B_update = new javax.swing.JButton();
        B_delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        T_key = new javax.swing.JTextField();
        T_birthd = new javax.swing.JTextField();
        T_birthm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        B_clear = new javax.swing.JButton();
        B_search = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("reto5");
        setBackground(new java.awt.Color(0, 51, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 3, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Attendance Sheet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 490, 110));

        Table.setBackground(new java.awt.Color(0, 0, 0));
        Table.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table.setAlignmentX(1.0F);
        Table.setAlignmentY(1.0F);
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 760, 970, 150));

        jLabel10.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Given Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 170, 40));

        jLabel23.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("User");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 150, 40));

        jLabel11.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SurName");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 150, 40));

        jLabel12.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("E-mail");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 150, 40));

        jLabel15.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 150, 40));

        jLabel16.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Search:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 120, 50));

        jLabel17.setFont(new java.awt.Font("Goudy Old Style", 3, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Birth Date");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 150, 40));

        T_user.setBackground(new java.awt.Color(0, 0, 0));
        T_user.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_user.setForeground(new java.awt.Color(255, 255, 255));
        T_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_userActionPerformed(evt);
            }
        });
        getContentPane().add(T_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 250, -1));

        T_givenname.setBackground(new java.awt.Color(0, 0, 0));
        T_givenname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_givenname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(T_givenname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 250, -1));

        T_surname.setBackground(new java.awt.Color(0, 0, 0));
        T_surname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_surname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(T_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 250, -1));

        T_email.setBackground(new java.awt.Color(0, 0, 0));
        T_email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_email.setForeground(new java.awt.Color(255, 255, 255));
        T_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_emailActionPerformed(evt);
            }
        });
        getContentPane().add(T_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 250, -1));

        T_phone.setBackground(new java.awt.Color(0, 0, 0));
        T_phone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_phone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(T_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 250, -1));

        T_birthy.setBackground(new java.awt.Color(0, 0, 0));
        T_birthy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_birthy.setForeground(new java.awt.Color(255, 255, 255));
        T_birthy.setToolTipText("");
        T_birthy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_birthyActionPerformed(evt);
            }
        });
        getContentPane().add(T_birthy, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 70, -1));

        T_search.setBackground(new java.awt.Color(0, 0, 0));
        T_search.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_search.setForeground(new java.awt.Color(255, 255, 255));
        T_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_searchActionPerformed(evt);
            }
        });
        T_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_searchKeyReleased(evt);
            }
        });
        getContentPane().add(T_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 690, 130, -1));

        B_create.setBackground(new java.awt.Color(0, 0, 0));
        B_create.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        B_create.setForeground(new java.awt.Color(255, 255, 255));
        B_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/add_icon-icons.com_74429.png"))); // NOI18N
        B_create.setText("Create");
        B_create.setDisabledIcon(null);
        B_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_createActionPerformed(evt);
            }
        });
        getContentPane().add(B_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 120, 50));

        B_update.setBackground(new java.awt.Color(0, 0, 0));
        B_update.setForeground(new java.awt.Color(255, 255, 255));
        B_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/sync.png"))); // NOI18N
        B_update.setText("Update");
        B_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_updateActionPerformed(evt);
            }
        });
        getContentPane().add(B_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 120, 50));

        B_delete.setBackground(new java.awt.Color(0, 0, 0));
        B_delete.setForeground(new java.awt.Color(255, 255, 255));
        B_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/delete_icon-icons.com_74434.png"))); // NOI18N
        B_delete.setText("Delete");
        B_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(B_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 120, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(51, 204, 0));
        jButton1.setText("Check DB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 100, 50));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, -1, -1));

        T_key.setBackground(new java.awt.Color(0, 0, 0));
        T_key.setForeground(new java.awt.Color(0, 0, 0));
        T_key.setBorder(null);
        T_key.setCaretColor(new java.awt.Color(0, 0, 0));
        T_key.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        T_key.setFocusable(false);
        T_key.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        T_key.setSelectionColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(T_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, -1, -1));

        T_birthd.setBackground(new java.awt.Color(0, 0, 0));
        T_birthd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_birthd.setForeground(new java.awt.Color(255, 255, 255));
        T_birthd.setToolTipText("");
        T_birthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_birthdActionPerformed(evt);
            }
        });
        getContentPane().add(T_birthd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 40, -1));

        T_birthm.setBackground(new java.awt.Color(0, 0, 0));
        T_birthm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        T_birthm.setForeground(new java.awt.Color(255, 255, 255));
        T_birthm.setToolTipText("");
        T_birthm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_birthmActionPerformed(evt);
            }
        });
        getContentPane().add(T_birthm, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 40, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("M");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Y");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("D");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, -1, 30));

        B_clear.setBackground(new java.awt.Color(0, 0, 0));
        B_clear.setForeground(new java.awt.Color(255, 255, 255));
        B_clear.setText("clear data");
        B_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_clearActionPerformed(evt);
            }
        });
        getContentPane().add(B_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, -1, -1));

        B_search.setBackground(new java.awt.Color(0, 0, 0));
        B_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/databasesearch_basededato_12920.png"))); // NOI18N
        B_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_searchActionPerformed(evt);
            }
        });
        getContentPane().add(B_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 680, 60, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/iconfinder-home-4341294_120570.png"))); // NOI18N
        home.setActionCommand("");
        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 910, 100, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/background start.jpg"))); // NOI18N
        jLabel1.setToolTipText("asas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 1010));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_userActionPerformed

    private void T_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_emailActionPerformed

    private void B_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_createActionPerformed

    Input();


    }//GEN-LAST:event_B_createActionPerformed

    private void T_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // check db button
         if (cc.conectar != null ) {
//        System.out.println ("Conectado");

      JOptionPane.showMessageDialog(null,"Successful connection", "Connection", JOptionPane.INFORMATION_MESSAGE);
      
      
    }
         else{
    JOptionPane.showMessageDialog(null,"Failed connnection","Connection", JOptionPane.INFORMATION_MESSAGE);
               
               
               
         }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void T_birthyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_birthyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_birthyActionPerformed

    private void T_birthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_birthdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_birthdActionPerformed

    private void T_birthmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_birthmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_birthmActionPerformed

    private void B_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_clearActionPerformed
        // clear data
       cleanbutton();
        
    }//GEN-LAST:event_B_clearActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Click any row in order to fill data
        
        int row=Table.rowAtPoint(evt.getPoint());
        
        T_user.setText(Table.getValueAt(row,1).toString());
        T_givenname.setText(Table.getValueAt(row,2).toString());
        T_surname.setText(Table.getValueAt(row,3).toString());
        T_email.setText(Table.getValueAt(row,4).toString());
        T_phone.setText(Table.getValueAt(row,5).toString());
//        T_key.setText(Table.getValueAt(row,6).toString());
           
        String[] parts = Table.getValueAt(row,6).toString().split("-");
        
        T_birthy.setText(parts[0]);
        T_birthm.setText(parts[1]);
        T_birthd.setText(parts[2]);
        
        
        
        
    }//GEN-LAST:event_TableMouseClicked

    private void B_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_updateActionPerformed
//update button event
   
    Update();
    cleanbutton();
    showdata();
    
    }//GEN-LAST:event_B_updateActionPerformed

    private void B_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_deleteActionPerformed
        // Delete button event
        
        Delete();
        cleanbutton();
        showdata();
    }//GEN-LAST:event_B_deleteActionPerformed

    private void B_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_searchActionPerformed
        // Finder
        
//        showfilter();
        showdata();
        
        
    }//GEN-LAST:event_B_searchActionPerformed

    private void T_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_searchKeyReleased
        // finderr key released
        
        
        String searchString = T_search.getText();
        finder(searchString);
        
        
        
    }//GEN-LAST:event_T_searchKeyReleased

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // home button
        
        asistencia START= new asistencia();
        START.setVisible(true);
        START.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
        
        
        
    }//GEN-LAST:event_homeActionPerformed

    public void showdata(){
        
        String[] title={"ID","User","Given Name","Surname","E-mail","Phone","Birth Date"};
        String[] records=new String[8];
        
        DefaultTableModel model=new DefaultTableModel(null,title);
        String SQL="SELECT * FROM asistente ORDER BY id DESC";
        try{
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            while(rs.next()){
                records[0]=rs.getString("id");

                records[1]=rs.getString("asi_login");
                 records[2]=rs.getString("asi_nombre");
                  records[3]=rs.getString("asi_apellido");
                   records[4]=rs.getString("usr_email");
                    records[5]=rs.getString("asi_celular");
                     records[6]=rs.getString("asi_fecha_n");
                     
                     
                    model.addRow(records);
                     
            }
            Table.setModel(model);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error"+ e.getMessage());
        }
        
    }
    
//    public void retrieve(){
//        int row=Table.getSelectedRow();
//        String user=(String)Table.getValueAt(row,0);
//        
//        int value;
//        String SQL="SELECT id FROM asistente Where asi_login='"+user+"';";
//        
//        
////        PreparedStatement pst;
//    try {
//        
//        Statement st=con.createStatement();
//         ResultSet rs=st.executeQuery(SQL);
//        String record=rs.getString("id");
//           
//           JOptionPane.showMessageDialog(null,"id"+rs);
//        
//    } catch (SQLException ex) {
//        Logger.getLogger(asistencia2.class.getName()).log(Level.SEVERE, null, ex);
//    }
//      
////          
//    
//    }
    

    
    
    
    public void finder(String str){
        
        model=  (DefaultTableModel) Table.getModel();
        TableRowSorter<DefaultTableModel> trs=new TableRowSorter<>(model);
        Table.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        
        
    }
      
    
    
    public void cleanbutton(){
        
        T_user.setText("");
        T_givenname.setText("");
        T_surname.setText("");
        T_email.setText("");
        T_phone.setText("");
        T_key.setText("");
           
        T_birthy.setText("");
        T_birthm.setText("");
        T_birthd.setText("");
        
        
    }
    
    public void Input(){
        try{
           
           String SQL="insert ignore into `asistente` (`asi_login`, `asi_nombre`, `asi_apellido`, `usr_email`, `asi_celular`, `asi_clave`,`asi_fecha_n`)  VALUES (?,?,?,?,?,?,?)";
//           String count = null;
           PreparedStatement pst=con.prepareStatement(SQL);
           
           pst.setString(1,T_user.getText());
           pst.setString(2,T_givenname.getText());
           pst.setString(3,T_surname.getText());
           pst.setString(4,T_email.getText());
           pst.setString(5,T_phone.getText());
           pst.setString(6,T_key.getText());
           
           String birth=(T_birthy.getText()+"-"+T_birthm.getText()+"-"+T_birthd.getText());
           pst.setString(7,birth);
      
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null,"Input Successfully");
       
            cleanbutton();

            showdata();


            
        }catch(Exception e){
                       JOptionPane.showMessageDialog(null,"Input Error" +e.getMessage());
                       

        }
        
    }
    
    
    
    
    
    
    public void Delete(){
        
        
        String value1=T_user.getText();
        try{
            String SQL ="DELETE FROM asistente WHERE asi_login='"+value1+"'";
            Statement st=con.createStatement();
            int n=st.executeUpdate(SQL);
            
            if(n>0){
                JOptionPane.showMessageDialog(null, "Record deleted");
            }
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Error deleting");
        }
        
        
    }
    
    
    
    public void Update(){
        try{
                                
           
          
        


           String value1=T_user.getText();
           String value2=T_givenname.getText();
           String value3=T_surname.getText();
           String value4=T_email.getText();
           String value5=T_phone.getText();
           
           String birth=(T_birthy.getText()+"-"+T_birthm.getText()+"-"+T_birthd.getText());
           
           int rowpick=Table.getSelectedRow();
           String rows =(String)Table.getValueAt(rowpick,0);
          
           String SQL="UPDATE asistente SET asi_login='"+value1+"',asi_nombre='"+value2+"',asi_apellido='"+value3+"',usr_email='"+value4+"',asi_celular='"+value5+"',asi_fecha_n='"+birth+"' WHERE id='"+rows+"'";
          
//           
//           
           PreparedStatement pst=con.prepareStatement(SQL);
      
            
            
//            ResultSet rs=st.executeQuery(SQL);
//      
//                      
//            records =rs.getString("id");
            
           pst=con.prepareStatement(SQL);
//           pst.setString(7,rows);
           pst.execute();
           
           JOptionPane.showMessageDialog(null,"Update record successful");
       
            cleanbutton();



            
        }catch(Exception e){
                       JOptionPane.showMessageDialog(null,"Update Error" +e.getMessage());
                       

        }
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asistencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asistencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asistencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asistencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asistencia2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_clear;
    private javax.swing.JButton B_create;
    private javax.swing.JButton B_delete;
    private javax.swing.JButton B_search;
    private javax.swing.JButton B_update;
    private javax.swing.JTextField T_birthd;
    private javax.swing.JTextField T_birthm;
    private javax.swing.JTextField T_birthy;
    private javax.swing.JTextField T_email;
    private javax.swing.JTextField T_givenname;
    private javax.swing.JTextField T_key;
    private javax.swing.JTextField T_phone;
    private javax.swing.JTextField T_search;
    private javax.swing.JTextField T_surname;
    private javax.swing.JTextField T_user;
    private javax.swing.JTable Table;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
